# APPLICATION INFO
spring.application.name=job-portal-applicant-tracking-system

# SERVER CONFIGURATION
server.port=8080

# DATABASE CONFIGURATION (PostgreSQL)
# Replace 'job_portal_db' with your actual database name
# Replace 'postgres' with your PostgreSQL username
# Replace 'your_password' with your PostgreSQL password
spring.datasource.url=jdbc:postgresql://localhost:5432/job-portal-applicant-tracking-system
spring.datasource.username=postgres
spring.datasource.password=root


# JPA / HIBERNATE CONFIGURATION
# update  \u2192 updates existing tables without dropping data
# create  \u2192 drops and recreates tables every time (loses data)
# validate\u2192 only validates, does not change schema
# none    \u2192 does nothing
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL for better readability in console
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect \u2014 tells Hibernate which DB we are using
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JACKSON (JSON) CONFIGURATION
# Do not include null fields in JSON response
spring.jackson.default-property-inclusion=non_null

# Format LocalDateTime as readable string not timestamp numbers
spring.jackson.serialization.write-dates-as-timestamps=false

# LOGGING CONFIGURATION
# Log level for your project package
logging.level.com.Neha.job_portal_applicant_tracking_system=DEBUG

# Log level for Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG

# Log actual values in queries
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# FILE UPLOAD CONFIGURATION
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ERROR HANDLING
server.error.include-message=always
server.error.include-binding-errors=always