package com.Neha.job_portal_applicant_tracking_system.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Candidate in the system.
 * A Candidate is a User with the CANDIDATE role who has created a profile with personal and professional details.
 * One User maps to exactly One Candidate — OneToOne relationship.
 * One Candidate can have Many Resumes and Many Applications.
 * Supports soft delete using the active flag.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "candidate")
public class Candidate {

	/** Unique identifier for the candidate — auto generated by database */
	 @Id
	 @GeneratedValue(strategy = GenerationType.IDENTITY)
	 @Column(name = "candidate_id")
	 private Long id;

	 /**
	  * First name of the candidate.
	  * Must be between 2 and 50 characters.
	  * Cannot be blank.
	  */
	 @NotBlank(message = "firstName is required")
	 @Size(min = 2, max = 50, message = "firstName must be between 2 and 50 characters")
	 @Column(nullable = false, name = "first_name")
	 private String firstName;

	 /**
	  * Last name of the candidate.
	  * Must be between 2 and 50 characters.
	  * Cannot be blank.
	  */
	 @NotBlank(message = "lastName is required")
	 @Size(min = 2, max = 50, message = "lastName must be between 2 and 50 characters")
	 @Column(nullable = false, name = "last_name")
	 private String lastName;

	 /**
	  * Email address of the candidate.
	  * Must be unique across the system.
	  * Cannot be blank.
	  */
	 @NotBlank(message = "email is required")
	 @Column(nullable = false, unique = true)
	 private String email;

	 /** Phone number of the candidate — cannot be blank */
	 @NotBlank(message = "phoneNumber is required")
	 @Column(nullable = false, name = "phone_number")
	 private String phoneNumber;

	 /**
	  * Date of birth of the candidate.
	  * Uses LocalDate — only stores date, not time. e.g. 1998-05-15
	  * Cannot be null.
	  */
	 @NotNull(message = "dateOfBirth is required")
	 @Column(name = "date_of_birth")
	 private LocalDate dateOfBirth;              

	 /**
	  * Gender of the candidate.
	  * Stored as string in DB using EnumType.STRING.
	  * Possible values — MALE, FEMALE, OTHER.
	  * Cannot be null.
	  */
	 @NotNull(message = "gender is required")
	 @Enumerated(EnumType.STRING)                 
	 @Column(nullable = false)
	 private Gender gender;

	 /**
	  * Current location of the candidate.* e.g. "Mumbai", "Delhi", "Bangalore".
	  * Cannot be blank.
	  */
	 @NotBlank(message = "currentLocation is required")
	 @Column(nullable = false, name = "current_location")
	 private String currentLocation;

	 /**
	  * Years of professional experience of the candidate.
	  * Cannot be negative — minimum value is 0.
	  * 0 means fresher candidate.
	  */
	 @Min(value = 0, message = "experienceYears cannot be negative")
	 @Column(nullable = false, name = "experience_years")
	 private int experienceYears;                 

	 /**
	  * Current job title of the candidate.
	  * Optional field — can be null for freshers e.g. "Junior Developer", "Software Engineer".
	  */
	 @Column(name = "current_job_title")
	 private String currentJobTitle;              

	 /**
	  * Current salary of the candidate.
	  * Optional field — candidate may not want to share.
	  * Uses BigDecimal for exact decimal precision.
	  * Cannot be negative — minimum value is 0.
	  */
	 @DecimalMin(value = "0.0", inclusive = true, message = "currentSalary cannot be negative")
	 @Column(name = "current_salary", precision = 10, scale = 2)
	 private BigDecimal currentSalary;            

	 /**
	  * Expected salary of the candidate.
	  * Optional field.
	  * Uses BigDecimal for exact decimal precision.
	  * Must be greater than 0 if provided.
	  */
	 @DecimalMin(value = "0.0", inclusive = false, message = "expectedSalary must be greater than 0")
	 @Column(name = "expected_salary", precision = 10, scale = 2)
	 private BigDecimal expectedSalary;           

	 /**
	  * Skills of the candidate.
	  * Stored as comma-separated string e.g. "Java, Spring Boot, MySQL".
	  * Cannot be blank.
	  * Cannot exceed 500 characters.
	  */
	 @NotBlank(message = "skills is required")
	 @Column(nullable = false, length = 500)
	 private String skills;                       

	 /**
	  * Indicates whether the candidate account is active.
	  * Set to false for soft delete — candidate still exists in DB.
	  * Default value is true when a new candidate is created.
	  */
	 @Column(nullable = false, name = "is_active")
	 private boolean active = true;

	 /**
	  * Timestamp when the candidate profile was created.
	  * Auto-set by Hibernate on INSERT — never updated.
	  */
	 @CreationTimestamp
	 @Column(updatable = false, name = "created_at")
	 private LocalDateTime createdAt;

	 /**
	  * Timestamp when the candidate profile was last updated.
	  * Auto-set by Hibernate on UPDATE.
	  */
	 @UpdateTimestamp
	 @Column(name = "updated_at")
	 private LocalDateTime updatedAt;
	    
	 /**
	  * User account linked to this candidate.
	  * One User maps to exactly One Candidate.
	  * unique = true ensures one user cannot have two candidate profiles.
	  * Loaded lazily for performance.
	  * Foreign key stored as user_id in the candidate table.
	  */
	 @NotNull(message = "user is required")
	 @OneToOne(fetch = FetchType.LAZY)
	 @JoinColumn(name = "user_id", nullable = false, unique = true)
	 //========== unique = true → one user can only be one candidate
	 private User user;
	 
	 /**
	  * List of resumes uploaded by this candidate.
	  * One Candidate can have Many Resumes.
	  * CascadeType.ALL — deleting candidate also deletes all resumes.
	  * orphanRemoval — resumes removed from list are deleted from DB.
	  * FetchType.LAZY — resumes loaded only when explicitly accessed.
	  */
	// One Candidate → Many Resumes
	 @OneToMany(
	     mappedBy = "candidate",
	     cascade = CascadeType.ALL,
	     orphanRemoval = true,       //===== deleting candidate also deletes all their resumes ========//
	     fetch = FetchType.LAZY
	 )
	 private List<Resume> resumes;
	
}
