package com.Neha.job_portal_applicant_tracking_system.entity;

import java.time.LocalDateTime;
import java.util.List;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Company in the system.
 * Companies are created by Recruiters and post Jobs.
 * One Company can have Many Jobs.
 * Supports soft delete using the active flag — deactivated companies still exist in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "company")
public class Company {

	/** Unique identifier for the company — auto generated by database */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "company_id")
	private Long id;
	
	 /**
     * Name of the company.
     * Must be unique across the system.
     * Must be between 2 and 100 characters.
     */
	@NotBlank(message = "companyName is required")
	@Size(min = 2,  max = 100, message = "companyName must be between 2 and 100 characters")
	@Column(nullable = false, unique = true, name = "company_name")
	private String companyName;
	
	/**
     * Brief description of the company.
     * Optional field — can be null.
     * Cannot exceed 500 characters.
     */
	@Size(max = 500, message = "description cannot exceed 500 characters")
	@Column(length = 500)
	private String description;
	
	/**
     * Official website URL of the company.
     * Optional field — can be null.
     * Must be in valid URL format if provided.
     * Must be unique across the system.
     */
	@Pattern(
			regexp = "^(https?://)?(www\\.)?[a-zA-Z0-9-]+(\\.[a-zA-Z]{2,})+(/.*)?$",
	        message = "Invalid website URL format"
			)
	@Column(unique = true)
	private String website;
	
	/**
     * Industry the company belongs to.
     * e.g. "IT", "Finance", "Healthcare".
     * Cannot be blank.
     */
	@NotBlank(message = "location is required")
	@Column(nullable = false)
	private String industry;
	
	/**
     * Physical location of the company.
     * e.g. "Mumbai", "Delhi", "Bangalore".
     * Cannot be blank.
     */
	@NotBlank(message = "location is required")
	@Column(nullable = false)
	private String location;
	
	/**
     * Indicates whether the company is active.
     * Set to false for soft delete — company still exists in DB.
     * Default value is true when a new company is created.
     */
	@Column(nullable = false, name = "is_active")
	private boolean active = true;
	
	/**
     * Timestamp when the company was created.
     * Auto-set by Hibernate on INSERT — never updated.
     */
	@CreationTimestamp
	@Column(updatable = false, name = "created_at")
	private LocalDateTime createdAt;
	
	/**
     * Timestamp when the company was last updated.
     * Auto-set by Hibernate on UPDATE.
     */
	@UpdateTimestamp
	@Column(name = "updated_at")
	private LocalDateTime updatedAt;
	
	/**
     * List of jobs posted by this company.
     * One Company can have Many Jobs.
     * CascadeType.ALL — deleting company also deletes all its jobs.
     * orphanRemoval — jobs removed from list are deleted from DB.
     * FetchType.LAZY — jobs loaded only when explicitly accessed.
     */
	// One Company → Many Jobs
    // mappedBy = "company" → refers to the field name in Job entity
    // cascade = ALL → any operation on Company cascades to its Jobs
    // orphanRemoval = true → if a Job is removed from the list, delete it from DB
    // fetch = LAZY → Jobs are only loaded when explicitly accessed (performance)
	@OneToMany(
			mappedBy = "company",
			cascade = CascadeType.ALL,
			orphanRemoval = true,
			fetch = FetchType.LAZY)
	private List<Job> jobs;
	
}
