package com.Neha.job_portal_applicant_tracking_system.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Job posted by a Company.
 * Contains details like title, salary, required skills
 * and experience needed for the position.
 * Many Jobs can belong to One Company.
 * Only OPEN jobs accept applications from candidates.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "job")
public class Job {

	/** Unique identifier for the job — auto generated by database */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "job_id")
	private Long id;
	
	/**
     * Title of the job position.
     * e.g. "Java Developer", "Data Analyst".
     * Must be between 2 and 100 characters.
     * Cannot be blank.
     */
	@NotBlank(message = "title is required")
	@Size(min = 2, max = 100, message = "title must be between 2 and 100 characters")
	@Column(nullable = false)
	private String title;
	
	/**
     * Detailed description of the job.
     * Cannot be blank.
     * Cannot exceed 1000 characters.
     */
	@NotBlank(message = "description is required")
    @Size(max = 1000, message = "description cannot exceed 1000 characters")
    @Column(nullable = false, length = 1000)
    private String description;

	/**
     * Skills required for this job position.
     * Stored as a comma-separated string.
     * e.g. "Java, Spring Boot, MySQL".
     * Cannot be blank.
     */
    @NotBlank(message = "requiredSkills is required")
    @Column(nullable = false, name = "required_skills")
    private String requiredSkills;
	
    /**
     * Years of experience required for this job.
     * Cannot be negative — minimum value is 0.
     * 0 means fresher candidates can apply.
     */
	@Min(value = 0, message = "experienceRequired cannot be negative ")
	@Column(nullable = false, name = "experience_required")
	private int experienceRequired;
	
	/**
     * Salary offered for this job position.
     * Uses BigDecimal for exact decimal precision.
     * Must be greater than 0.
     * Stored with precision 10 and scale 2.
     * e.g. 75000.00
     */
	@NotNull(message = "salary is reqired")
	@DecimalMin(value = "0.0", inclusive = false, message = "salary must be greater than 0")
	@Column(nullable = false, precision = 10, scale = 2)
	private BigDecimal salary;
	
	/**
     * Location where the job is based.
     * e.g. "Mumbai", "Delhi", "Remote".
     * Cannot be blank.
     */
	@NotBlank(message = "location is required")
	@Column(nullable = false)
	private String location;
	
	/**
     * Type of the job.
     * Stored as string in DB using EnumType.STRING.
     * Possible values — FULL_TIME, PART_TIME, CONTRACT,
     * INTERNSHIP, FREELANCE, REMOTE.
     */
	@NotNull(message = "jobType is required")
    @Enumerated(EnumType.STRING)               // Stores "FULL_TIME" not 0/1 in DB
    @Column(nullable = false, name = "job_type")
    private JobType jobType;
	
	/**
     * Current status of the job.
     * Stored as string in DB using EnumType.STRING.
     * Possible values — OPEN, CLOSED, ON_HOLD, FILLED.
     * Default value is OPEN when a new job is created.
     * Only OPEN jobs accept applications.
     */
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private JobStatus status = JobStatus.OPEN;
	
	/**
     * Timestamp when the job was created.
     * Auto-set by Hibernate on INSERT — never updated.
     */
	@CreationTimestamp
    @Column(updatable = false, name = "created_at")
	private LocalDateTime createdAt;
	
	/**
     * Timestamp when the job was last updated.
     * Auto-set by Hibernate on UPDATE.
     */
	@UpdateTimestamp
    @Column(name = "updated_at")
	private LocalDateTime updatedAt;
	
	/**
     * Company that posted this job.
     * Many Jobs belong to One Company.
     * Loaded lazily for performance — only fetched when accessed.
     * Foreign key stored as company_id in the job table.
     */
	@NotNull(message = "company is required")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id", nullable = false)
	private Company company;
}
