package com.Neha.job_portal_applicant_tracking_system.entity;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Role in the system.
 * Defines the type of user — Admin, Recruiter or Candidate.
 * Every User must be assigned exactly one Role.
 * Role controls what actions a user is allowed to perform.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class Role {

	 /** Unique identifier for the role — auto generated by database */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "role_id")
	private Long id;
	
	/**
     * Name of the role.
     * Expected values — ADMIN, RECRUITER, CANDIDATE.
     * Must be unique and cannot be blank.
     */
	@NotBlank(message = "role is required")
	@Column(nullable = false)
	private String role;
}
