package com.Neha.job_portal_applicant_tracking_system.entity;

import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.ManyToAny;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a User in the system.
 * Every person — Admin, Recruiter and Candidate —
 * must first be registered as a User with a Role assigned.
 * Sensitive fields like password are never exposed in response DTOs.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "users")
public class User {

	/** Unique identifier for the user — auto generated by database */
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Id
	@Column(name = "user_id")
	private Long id;
	
	/** First name of the user — cannot be blank */
	@NotBlank(message = "firstName is required")
	private String firstName;
	
	/** Last name of the user — cannot be blank */
	@NotBlank(message = "lastName is required")
	private String lastName;
	
	/**
     * Email address of the user.
     * Must be unique across the system — used as login identifier.
     */
	@NotBlank(message = "email is required")
	@Email(message = "invalid email format")
	@Column(nullable = false, unique = true)
	private String email;
	
	/**
     * Encrypted password of the user.
     * Never returned in any API response.
     */
	@NotBlank(message = "password is required")
	private String password;
	
	/** Phone number of the user — cannot be blank */
	@NotBlank(message = "phoneNumber is required")
	private String phoneNumber;
	
	/**
     * Indicates whether the user account is active.
     * Set to false for soft delete — user still exists in DB.
     * Default value is true when a new user is created.
     */
	@Column(nullable = false, name = "is_active")
	private boolean active = true;
	
	/**
     * Timestamp when the user was created.
     * Auto-set by Hibernate on INSERT — never updated.
     */
	@CreationTimestamp
	private LocalDateTime createdAt;
	
	 /**
     * Timestamp when the user was last updated.
     * Manually set in service layer when user details change.
     */
	private LocalDateTime updatedAt;
	
	/**
     * Role assigned to this user — Admin, Recruiter or Candidate.
     * Loaded lazily for performance — only fetched when accessed.
     * Foreign key stored as role_id in the users table.
     */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false) //@JoinColumn => Specifies the foreign key column that links two tables together. name = "role_id" => The actual column name in the database table will be role_id. nullable = false => The foreign key column cannot be NULL — meaning every record must have an associated role.
	private Role role;
	
}
